FROM php:7.0.33-apache
#FROM mobtitude/php-xdebug:7.0-apache
ENV MYSQL_DATABASE=mysql
ENV MYSQL_USER=mysql
ENV MYSQL_PASSWORD=mypassword
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=password

ENV MONGO_DB=mongo

RUN pecl channel-update pecl.php.net \
  && pecl install xdebug-2.7.2 \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN apt-get update \
  && apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev \
  && apt-get install -y libcurl4-openssl-dev pkg-config \
  && apt-get install -y libsasl2-dev \
  && docker-php-ext-install pdo pdo_mysql mysqli \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install mongodb-1.2.9
RUN echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini

WORKDIR /var/www/html
EXPOSE 80
COPY ./*.php ./.
CMD ["apache2-foreground"]



